name: Android Build (Kivy)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk python3-pip python3-setuptools libffi-dev libssl-dev

      - name: Set environment
        run: |
          echo "PATH=$ANDROID_HOME/cmdline-tools/latest/bin:$PATH" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install Build Tools
        run: sdkmanager "build-tools;34.0.0" "platforms;android-31"

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      - name: Build APK
        run: |
          buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: hello-world-apk
          path: bin/*.apk
