name: Build Hello World Kivy App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.8'

    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk python3-pip \
          libncurses5 libstdc++6 libffi-dev libssl-dev libsqlite3-dev zlib1g-dev liblzma-dev \
          autoconf automake cmake libtool pkg-config

    - name: Upgrade pip and install Python tools
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython==0.29.33

    - name: Cache Buildozer
      uses: actions/cache@v4
      with:
        path: ~/.buildozer
        key: buildozer-cache-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: hello-world-apk
        path: bin/*.apk
